#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLDependencyGraph
{
    using System.Data.Linq.Mapping;
    using System.Linq;
    using System.Reflection;



    public partial class DbInfo : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DbInfo() : 
				base("Data Source=.;Initial Catalog=DestSQLDatabase;Integrated Security=True;Pooling=Fa" +
						"lse;MultipleActiveResultSets=True", mappingSource)
		{
			OnCreated();
		}
		
		public DbInfo(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbInfo(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbInfo(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DbInfo(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<all_object> all_objects
		{
			get
			{
				return this.GetTable<all_object>();
			}
		}
		
		public System.Data.Linq.Table<schema> schemas
		{
			get
			{
				return this.GetTable<schema>();
			}
		}
		
		public System.Data.Linq.Table<database> databases
		{
			get
			{
				return this.GetTable<database>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sys.dm_sql_referenced_entities", IsComposable=true)]
		public IQueryable<dm_sql_referenced_entitiesResult> dm_sql_referenced_entities([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(517)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(60)")] string referencing_class)
		{
			return this.CreateMethodCallQuery<dm_sql_referenced_entitiesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, referencing_class);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="sys.dm_sql_referencing_entities", IsComposable=true)]
		public IQueryable<dm_sql_referencing_entitiesResult> dm_sql_referencing_entities([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(517)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(60)")] string referenced_class)
		{
			return this.CreateMethodCallQuery<dm_sql_referencing_entitiesResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, referenced_class);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.all_objects")]
	public partial class all_object
	{
		
		private string _name;
		
		private int _object_id;
		
		private System.Nullable<int> _principal_id;
		
		private int _schema_id;
		
		private int _parent_object_id;
		
		private string _type;
		
		private string _type_desc;
		
		private System.DateTime _create_date;
		
		private System.DateTime _modify_date;
		
		private bool _is_ms_shipped;
		
		private bool _is_published;
		
		private bool _is_schema_published;
		
		public all_object()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_object_id", DbType="Int NOT NULL")]
		public int object_id
		{
			get
			{
				return this._object_id;
			}
			set
			{
				if ((this._object_id != value))
				{
					this._object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent_object_id", DbType="Int NOT NULL")]
		public int parent_object_id
		{
			get
			{
				return this._parent_object_id;
			}
			set
			{
				if ((this._parent_object_id != value))
				{
					this._parent_object_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string type
		{
			get
			{
				return this._type;
			}
			set
			{
				if ((this._type != value))
				{
					this._type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type_desc", DbType="NVarChar(60)")]
		public string type_desc
		{
			get
			{
				return this._type_desc;
			}
			set
			{
				if ((this._type_desc != value))
				{
					this._type_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime NOT NULL")]
		public System.DateTime modify_date
		{
			get
			{
				return this._modify_date;
			}
			set
			{
				if ((this._modify_date != value))
				{
					this._modify_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ms_shipped", DbType="Bit NOT NULL")]
		public bool is_ms_shipped
		{
			get
			{
				return this._is_ms_shipped;
			}
			set
			{
				if ((this._is_ms_shipped != value))
				{
					this._is_ms_shipped = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_schema_published", DbType="Bit NOT NULL")]
		public bool is_schema_published
		{
			get
			{
				return this._is_schema_published;
			}
			set
			{
				if ((this._is_schema_published != value))
				{
					this._is_schema_published = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.schemas")]
	public partial class schema
	{
		
		private string _name;
		
		private int _schema_id;
		
		private System.Nullable<int> _principal_id;
		
		public schema()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schema_id", DbType="Int NOT NULL")]
		public int schema_id
		{
			get
			{
				return this._schema_id;
			}
			set
			{
				if ((this._schema_id != value))
				{
					this._schema_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_principal_id", DbType="Int")]
		public System.Nullable<int> principal_id
		{
			get
			{
				return this._principal_id;
			}
			set
			{
				if ((this._principal_id != value))
				{
					this._principal_id = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="sys.databases")]
	public partial class database
	{
		
		private string _name;
		
		private int _database_id;
		
		private System.Nullable<int> _source_database_id;
		
		private System.Data.Linq.Binary _owner_sid;
		
		private System.DateTime _create_date;
		
		private byte _compatibility_level;
		
		private string _collation_name;
		
		private System.Nullable<byte> _user_access;
		
		private string _user_access_desc;
		
		private System.Nullable<bool> _is_read_only;
		
		private bool _is_auto_close_on;
		
		private System.Nullable<bool> _is_auto_shrink_on;
		
		private System.Nullable<byte> _state;
		
		private string _state_desc;
		
		private System.Nullable<bool> _is_in_standby;
		
		private System.Nullable<bool> _is_cleanly_shutdown;
		
		private System.Nullable<bool> _is_supplemental_logging_enabled;
		
		private System.Nullable<byte> _snapshot_isolation_state;
		
		private string _snapshot_isolation_state_desc;
		
		private System.Nullable<bool> _is_read_committed_snapshot_on;
		
		private System.Nullable<byte> _recovery_model;
		
		private string _recovery_model_desc;
		
		private System.Nullable<byte> _page_verify_option;
		
		private string _page_verify_option_desc;
		
		private System.Nullable<bool> _is_auto_create_stats_on;
		
		private System.Nullable<bool> _is_auto_update_stats_on;
		
		private System.Nullable<bool> _is_auto_update_stats_async_on;
		
		private System.Nullable<bool> _is_ansi_null_default_on;
		
		private System.Nullable<bool> _is_ansi_nulls_on;
		
		private System.Nullable<bool> _is_ansi_padding_on;
		
		private System.Nullable<bool> _is_ansi_warnings_on;
		
		private System.Nullable<bool> _is_arithabort_on;
		
		private System.Nullable<bool> _is_concat_null_yields_null_on;
		
		private System.Nullable<bool> _is_numeric_roundabort_on;
		
		private System.Nullable<bool> _is_quoted_identifier_on;
		
		private System.Nullable<bool> _is_recursive_triggers_on;
		
		private System.Nullable<bool> _is_cursor_close_on_commit_on;
		
		private System.Nullable<bool> _is_local_cursor_default;
		
		private System.Nullable<bool> _is_fulltext_enabled;
		
		private System.Nullable<bool> _is_trustworthy_on;
		
		private System.Nullable<bool> _is_db_chaining_on;
		
		private System.Nullable<bool> _is_parameterization_forced;
		
		private bool _is_master_key_encrypted_by_server;
		
		private bool _is_published;
		
		private bool _is_subscribed;
		
		private bool _is_merge_published;
		
		private bool _is_distributor;
		
		private bool _is_sync_with_backup;
		
		private System.Guid _service_broker_guid;
		
		private bool _is_broker_enabled;
		
		private System.Nullable<byte> _log_reuse_wait;
		
		private string _log_reuse_wait_desc;
		
		private bool _is_date_correlation_on;
		
		private bool _is_cdc_enabled;
		
		private System.Nullable<bool> _is_encrypted;
		
		private System.Nullable<bool> _is_honor_broker_priority_on;
		
		public database()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_database_id", DbType="Int NOT NULL")]
		public int database_id
		{
			get
			{
				return this._database_id;
			}
			set
			{
				if ((this._database_id != value))
				{
					this._database_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_source_database_id", DbType="Int")]
		public System.Nullable<int> source_database_id
		{
			get
			{
				return this._source_database_id;
			}
			set
			{
				if ((this._source_database_id != value))
				{
					this._source_database_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_owner_sid", DbType="VarBinary(85)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary owner_sid
		{
			get
			{
				return this._owner_sid;
			}
			set
			{
				if ((this._owner_sid != value))
				{
					this._owner_sid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime NOT NULL")]
		public System.DateTime create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_compatibility_level", DbType="TinyInt NOT NULL")]
		public byte compatibility_level
		{
			get
			{
				return this._compatibility_level;
			}
			set
			{
				if ((this._compatibility_level != value))
				{
					this._compatibility_level = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_collation_name", DbType="NVarChar(128)")]
		public string collation_name
		{
			get
			{
				return this._collation_name;
			}
			set
			{
				if ((this._collation_name != value))
				{
					this._collation_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_access", DbType="TinyInt")]
		public System.Nullable<byte> user_access
		{
			get
			{
				return this._user_access;
			}
			set
			{
				if ((this._user_access != value))
				{
					this._user_access = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_access_desc", DbType="NVarChar(60)")]
		public string user_access_desc
		{
			get
			{
				return this._user_access_desc;
			}
			set
			{
				if ((this._user_access_desc != value))
				{
					this._user_access_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_read_only", DbType="Bit")]
		public System.Nullable<bool> is_read_only
		{
			get
			{
				return this._is_read_only;
			}
			set
			{
				if ((this._is_read_only != value))
				{
					this._is_read_only = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_close_on", DbType="Bit NOT NULL")]
		public bool is_auto_close_on
		{
			get
			{
				return this._is_auto_close_on;
			}
			set
			{
				if ((this._is_auto_close_on != value))
				{
					this._is_auto_close_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_shrink_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_shrink_on
		{
			get
			{
				return this._is_auto_shrink_on;
			}
			set
			{
				if ((this._is_auto_shrink_on != value))
				{
					this._is_auto_shrink_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="TinyInt")]
		public System.Nullable<byte> state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state_desc", DbType="NVarChar(60)")]
		public string state_desc
		{
			get
			{
				return this._state_desc;
			}
			set
			{
				if ((this._state_desc != value))
				{
					this._state_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_in_standby", DbType="Bit")]
		public System.Nullable<bool> is_in_standby
		{
			get
			{
				return this._is_in_standby;
			}
			set
			{
				if ((this._is_in_standby != value))
				{
					this._is_in_standby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_cleanly_shutdown", DbType="Bit")]
		public System.Nullable<bool> is_cleanly_shutdown
		{
			get
			{
				return this._is_cleanly_shutdown;
			}
			set
			{
				if ((this._is_cleanly_shutdown != value))
				{
					this._is_cleanly_shutdown = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_supplemental_logging_enabled", DbType="Bit")]
		public System.Nullable<bool> is_supplemental_logging_enabled
		{
			get
			{
				return this._is_supplemental_logging_enabled;
			}
			set
			{
				if ((this._is_supplemental_logging_enabled != value))
				{
					this._is_supplemental_logging_enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snapshot_isolation_state", DbType="TinyInt")]
		public System.Nullable<byte> snapshot_isolation_state
		{
			get
			{
				return this._snapshot_isolation_state;
			}
			set
			{
				if ((this._snapshot_isolation_state != value))
				{
					this._snapshot_isolation_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_snapshot_isolation_state_desc", DbType="NVarChar(60)")]
		public string snapshot_isolation_state_desc
		{
			get
			{
				return this._snapshot_isolation_state_desc;
			}
			set
			{
				if ((this._snapshot_isolation_state_desc != value))
				{
					this._snapshot_isolation_state_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_read_committed_snapshot_on", DbType="Bit")]
		public System.Nullable<bool> is_read_committed_snapshot_on
		{
			get
			{
				return this._is_read_committed_snapshot_on;
			}
			set
			{
				if ((this._is_read_committed_snapshot_on != value))
				{
					this._is_read_committed_snapshot_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recovery_model", DbType="TinyInt")]
		public System.Nullable<byte> recovery_model
		{
			get
			{
				return this._recovery_model;
			}
			set
			{
				if ((this._recovery_model != value))
				{
					this._recovery_model = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recovery_model_desc", DbType="NVarChar(60)")]
		public string recovery_model_desc
		{
			get
			{
				return this._recovery_model_desc;
			}
			set
			{
				if ((this._recovery_model_desc != value))
				{
					this._recovery_model_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_verify_option", DbType="TinyInt")]
		public System.Nullable<byte> page_verify_option
		{
			get
			{
				return this._page_verify_option;
			}
			set
			{
				if ((this._page_verify_option != value))
				{
					this._page_verify_option = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_page_verify_option_desc", DbType="NVarChar(60)")]
		public string page_verify_option_desc
		{
			get
			{
				return this._page_verify_option_desc;
			}
			set
			{
				if ((this._page_verify_option_desc != value))
				{
					this._page_verify_option_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_create_stats_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_create_stats_on
		{
			get
			{
				return this._is_auto_create_stats_on;
			}
			set
			{
				if ((this._is_auto_create_stats_on != value))
				{
					this._is_auto_create_stats_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_update_stats_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_update_stats_on
		{
			get
			{
				return this._is_auto_update_stats_on;
			}
			set
			{
				if ((this._is_auto_update_stats_on != value))
				{
					this._is_auto_update_stats_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_auto_update_stats_async_on", DbType="Bit")]
		public System.Nullable<bool> is_auto_update_stats_async_on
		{
			get
			{
				return this._is_auto_update_stats_async_on;
			}
			set
			{
				if ((this._is_auto_update_stats_async_on != value))
				{
					this._is_auto_update_stats_async_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_null_default_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_null_default_on
		{
			get
			{
				return this._is_ansi_null_default_on;
			}
			set
			{
				if ((this._is_ansi_null_default_on != value))
				{
					this._is_ansi_null_default_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_nulls_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_nulls_on
		{
			get
			{
				return this._is_ansi_nulls_on;
			}
			set
			{
				if ((this._is_ansi_nulls_on != value))
				{
					this._is_ansi_nulls_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_padding_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_padding_on
		{
			get
			{
				return this._is_ansi_padding_on;
			}
			set
			{
				if ((this._is_ansi_padding_on != value))
				{
					this._is_ansi_padding_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ansi_warnings_on", DbType="Bit")]
		public System.Nullable<bool> is_ansi_warnings_on
		{
			get
			{
				return this._is_ansi_warnings_on;
			}
			set
			{
				if ((this._is_ansi_warnings_on != value))
				{
					this._is_ansi_warnings_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_arithabort_on", DbType="Bit")]
		public System.Nullable<bool> is_arithabort_on
		{
			get
			{
				return this._is_arithabort_on;
			}
			set
			{
				if ((this._is_arithabort_on != value))
				{
					this._is_arithabort_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_concat_null_yields_null_on", DbType="Bit")]
		public System.Nullable<bool> is_concat_null_yields_null_on
		{
			get
			{
				return this._is_concat_null_yields_null_on;
			}
			set
			{
				if ((this._is_concat_null_yields_null_on != value))
				{
					this._is_concat_null_yields_null_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_numeric_roundabort_on", DbType="Bit")]
		public System.Nullable<bool> is_numeric_roundabort_on
		{
			get
			{
				return this._is_numeric_roundabort_on;
			}
			set
			{
				if ((this._is_numeric_roundabort_on != value))
				{
					this._is_numeric_roundabort_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_quoted_identifier_on", DbType="Bit")]
		public System.Nullable<bool> is_quoted_identifier_on
		{
			get
			{
				return this._is_quoted_identifier_on;
			}
			set
			{
				if ((this._is_quoted_identifier_on != value))
				{
					this._is_quoted_identifier_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_recursive_triggers_on", DbType="Bit")]
		public System.Nullable<bool> is_recursive_triggers_on
		{
			get
			{
				return this._is_recursive_triggers_on;
			}
			set
			{
				if ((this._is_recursive_triggers_on != value))
				{
					this._is_recursive_triggers_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_cursor_close_on_commit_on", DbType="Bit")]
		public System.Nullable<bool> is_cursor_close_on_commit_on
		{
			get
			{
				return this._is_cursor_close_on_commit_on;
			}
			set
			{
				if ((this._is_cursor_close_on_commit_on != value))
				{
					this._is_cursor_close_on_commit_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_local_cursor_default", DbType="Bit")]
		public System.Nullable<bool> is_local_cursor_default
		{
			get
			{
				return this._is_local_cursor_default;
			}
			set
			{
				if ((this._is_local_cursor_default != value))
				{
					this._is_local_cursor_default = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_fulltext_enabled", DbType="Bit")]
		public System.Nullable<bool> is_fulltext_enabled
		{
			get
			{
				return this._is_fulltext_enabled;
			}
			set
			{
				if ((this._is_fulltext_enabled != value))
				{
					this._is_fulltext_enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_trustworthy_on", DbType="Bit")]
		public System.Nullable<bool> is_trustworthy_on
		{
			get
			{
				return this._is_trustworthy_on;
			}
			set
			{
				if ((this._is_trustworthy_on != value))
				{
					this._is_trustworthy_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_db_chaining_on", DbType="Bit")]
		public System.Nullable<bool> is_db_chaining_on
		{
			get
			{
				return this._is_db_chaining_on;
			}
			set
			{
				if ((this._is_db_chaining_on != value))
				{
					this._is_db_chaining_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_parameterization_forced", DbType="Bit")]
		public System.Nullable<bool> is_parameterization_forced
		{
			get
			{
				return this._is_parameterization_forced;
			}
			set
			{
				if ((this._is_parameterization_forced != value))
				{
					this._is_parameterization_forced = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_master_key_encrypted_by_server", DbType="Bit NOT NULL")]
		public bool is_master_key_encrypted_by_server
		{
			get
			{
				return this._is_master_key_encrypted_by_server;
			}
			set
			{
				if ((this._is_master_key_encrypted_by_server != value))
				{
					this._is_master_key_encrypted_by_server = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_published", DbType="Bit NOT NULL")]
		public bool is_published
		{
			get
			{
				return this._is_published;
			}
			set
			{
				if ((this._is_published != value))
				{
					this._is_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_subscribed", DbType="Bit NOT NULL")]
		public bool is_subscribed
		{
			get
			{
				return this._is_subscribed;
			}
			set
			{
				if ((this._is_subscribed != value))
				{
					this._is_subscribed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_merge_published", DbType="Bit NOT NULL")]
		public bool is_merge_published
		{
			get
			{
				return this._is_merge_published;
			}
			set
			{
				if ((this._is_merge_published != value))
				{
					this._is_merge_published = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_distributor", DbType="Bit NOT NULL")]
		public bool is_distributor
		{
			get
			{
				return this._is_distributor;
			}
			set
			{
				if ((this._is_distributor != value))
				{
					this._is_distributor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_sync_with_backup", DbType="Bit NOT NULL")]
		public bool is_sync_with_backup
		{
			get
			{
				return this._is_sync_with_backup;
			}
			set
			{
				if ((this._is_sync_with_backup != value))
				{
					this._is_sync_with_backup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_service_broker_guid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid service_broker_guid
		{
			get
			{
				return this._service_broker_guid;
			}
			set
			{
				if ((this._service_broker_guid != value))
				{
					this._service_broker_guid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_broker_enabled", DbType="Bit NOT NULL")]
		public bool is_broker_enabled
		{
			get
			{
				return this._is_broker_enabled;
			}
			set
			{
				if ((this._is_broker_enabled != value))
				{
					this._is_broker_enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_reuse_wait", DbType="TinyInt")]
		public System.Nullable<byte> log_reuse_wait
		{
			get
			{
				return this._log_reuse_wait;
			}
			set
			{
				if ((this._log_reuse_wait != value))
				{
					this._log_reuse_wait = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_log_reuse_wait_desc", DbType="NVarChar(60)")]
		public string log_reuse_wait_desc
		{
			get
			{
				return this._log_reuse_wait_desc;
			}
			set
			{
				if ((this._log_reuse_wait_desc != value))
				{
					this._log_reuse_wait_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_date_correlation_on", DbType="Bit NOT NULL")]
		public bool is_date_correlation_on
		{
			get
			{
				return this._is_date_correlation_on;
			}
			set
			{
				if ((this._is_date_correlation_on != value))
				{
					this._is_date_correlation_on = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_cdc_enabled", DbType="Bit NOT NULL")]
		public bool is_cdc_enabled
		{
			get
			{
				return this._is_cdc_enabled;
			}
			set
			{
				if ((this._is_cdc_enabled != value))
				{
					this._is_cdc_enabled = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_encrypted", DbType="Bit")]
		public System.Nullable<bool> is_encrypted
		{
			get
			{
				return this._is_encrypted;
			}
			set
			{
				if ((this._is_encrypted != value))
				{
					this._is_encrypted = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_honor_broker_priority_on", DbType="Bit")]
		public System.Nullable<bool> is_honor_broker_priority_on
		{
			get
			{
				return this._is_honor_broker_priority_on;
			}
			set
			{
				if ((this._is_honor_broker_priority_on != value))
				{
					this._is_honor_broker_priority_on = value;
				}
			}
		}
	}
	
	public partial class dm_sql_referenced_entitiesResult
	{
		
		private System.Nullable<int> _referencing_minor_id;
		
		private string _referenced_server_name;
		
		private string _referenced_database_name;
		
		private string _referenced_schema_name;
		
		private string _referenced_entity_name;
		
		private string _referenced_minor_name;
		
		private System.Nullable<int> _referenced_id;
		
		private System.Nullable<int> _referenced_minor_id;
		
		private System.Nullable<byte> _referenced_class;
		
		private string _referenced_class_desc;
		
		private bool _is_caller_dependent;
		
		private bool _is_ambiguous;
		
		public dm_sql_referenced_entitiesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencing_minor_id", DbType="Int")]
		public System.Nullable<int> referencing_minor_id
		{
			get
			{
				return this._referencing_minor_id;
			}
			set
			{
				if ((this._referencing_minor_id != value))
				{
					this._referencing_minor_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_server_name", DbType="NVarChar(128)")]
		public string referenced_server_name
		{
			get
			{
				return this._referenced_server_name;
			}
			set
			{
				if ((this._referenced_server_name != value))
				{
					this._referenced_server_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_database_name", DbType="NVarChar(128)")]
		public string referenced_database_name
		{
			get
			{
				return this._referenced_database_name;
			}
			set
			{
				if ((this._referenced_database_name != value))
				{
					this._referenced_database_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_schema_name", DbType="NVarChar(128)")]
		public string referenced_schema_name
		{
			get
			{
				return this._referenced_schema_name;
			}
			set
			{
				if ((this._referenced_schema_name != value))
				{
					this._referenced_schema_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_entity_name", DbType="NVarChar(128)")]
		public string referenced_entity_name
		{
			get
			{
				return this._referenced_entity_name;
			}
			set
			{
				if ((this._referenced_entity_name != value))
				{
					this._referenced_entity_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_minor_name", DbType="NVarChar(128)")]
		public string referenced_minor_name
		{
			get
			{
				return this._referenced_minor_name;
			}
			set
			{
				if ((this._referenced_minor_name != value))
				{
					this._referenced_minor_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_id", DbType="Int")]
		public System.Nullable<int> referenced_id
		{
			get
			{
				return this._referenced_id;
			}
			set
			{
				if ((this._referenced_id != value))
				{
					this._referenced_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_minor_id", DbType="Int")]
		public System.Nullable<int> referenced_minor_id
		{
			get
			{
				return this._referenced_minor_id;
			}
			set
			{
				if ((this._referenced_minor_id != value))
				{
					this._referenced_minor_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_class", DbType="TinyInt")]
		public System.Nullable<byte> referenced_class
		{
			get
			{
				return this._referenced_class;
			}
			set
			{
				if ((this._referenced_class != value))
				{
					this._referenced_class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referenced_class_desc", DbType="NVarChar(60)")]
		public string referenced_class_desc
		{
			get
			{
				return this._referenced_class_desc;
			}
			set
			{
				if ((this._referenced_class_desc != value))
				{
					this._referenced_class_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_caller_dependent", DbType="Bit NOT NULL")]
		public bool is_caller_dependent
		{
			get
			{
				return this._is_caller_dependent;
			}
			set
			{
				if ((this._is_caller_dependent != value))
				{
					this._is_caller_dependent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_ambiguous", DbType="Bit NOT NULL")]
		public bool is_ambiguous
		{
			get
			{
				return this._is_ambiguous;
			}
			set
			{
				if ((this._is_ambiguous != value))
				{
					this._is_ambiguous = value;
				}
			}
		}
	}
	
	public partial class dm_sql_referencing_entitiesResult
	{
		
		private string _referencing_schema_name;
		
		private string _referencing_entity_name;
		
		private int _referencing_id;
		
		private System.Nullable<byte> _referencing_class;
		
		private string _referencing_class_desc;
		
		private bool _is_caller_dependent;
		
		public dm_sql_referencing_entitiesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencing_schema_name", DbType="NVarChar(128)")]
		public string referencing_schema_name
		{
			get
			{
				return this._referencing_schema_name;
			}
			set
			{
				if ((this._referencing_schema_name != value))
				{
					this._referencing_schema_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencing_entity_name", DbType="NVarChar(128)")]
		public string referencing_entity_name
		{
			get
			{
				return this._referencing_entity_name;
			}
			set
			{
				if ((this._referencing_entity_name != value))
				{
					this._referencing_entity_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencing_id", DbType="Int NOT NULL")]
		public int referencing_id
		{
			get
			{
				return this._referencing_id;
			}
			set
			{
				if ((this._referencing_id != value))
				{
					this._referencing_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencing_class", DbType="TinyInt")]
		public System.Nullable<byte> referencing_class
		{
			get
			{
				return this._referencing_class;
			}
			set
			{
				if ((this._referencing_class != value))
				{
					this._referencing_class = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_referencing_class_desc", DbType="NVarChar(60)")]
		public string referencing_class_desc
		{
			get
			{
				return this._referencing_class_desc;
			}
			set
			{
				if ((this._referencing_class_desc != value))
				{
					this._referencing_class_desc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_caller_dependent", DbType="Bit NOT NULL")]
		public bool is_caller_dependent
		{
			get
			{
				return this._is_caller_dependent;
			}
			set
			{
				if ((this._is_caller_dependent != value))
				{
					this._is_caller_dependent = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
